name: Build Python Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  actions: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: arti-python
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build --outdir build_artifacts  # Corrected argument here to '--outdir'

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: arti-python
          path: build_artifacts/  # Updated path here to match new output directory
          if-no-files-found: error
          retention-days: 10
          overwrite: true  # Enable overwriting of artifacts with the same name
