name: Publish Python Package

on:
  push:
    branches:
      - master

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read
  actions: write

env:
  CLOUDSMITH_NAMESPACE: Interview-Ashish-Dwivedi
  CLOUDSMITH_REPOSITORY: ci-cdtrial

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Cloudsmith CLI
      - name: Install Cloudsmith CLI
        run: |
          python -m pip install --upgrade pip
          pip install cloudsmith-cli

      # Download artifact from previous workflow (if applicable)
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist/  # Updated path here to 'dist/'

      # List directory contents (for debugging)
      - name: List directory contents
        run: ls -la dist/  # Updated path here to 'dist/'

      # Push package to Cloudsmith
      - name: Push package to Cloudsmith
        run: |
          if ! ls dist/*.tar.gz 1> /dev/null 2>&1; then  # Updated path here to 'dist/'
            echo "No package found to upload"
            exit 1
          fi
          cloudsmith push python ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_REPOSITORY }} dist/*.tar.gz --republish  # Updated path here to 'dist/'
