name: Publish Python Package

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed
    branches:
      - master

permissions:
  id-token: write  # Required for OIDC authentication
  contents: write
  actions: write

env:
  CLOUDSMITH_NAMESPACE: Interview-Ashish-Dwivedi
  CLOUDSMITH_REPOSITORY: ci-cdtrial
  #CLOUDSMITH_SERVICE_SLUG: ci-cdtrial

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Cloudsmith CLI
      - name: Install Cloudsmith CLI
        run: |
          python -m pip install --upgrade pip
          pip install cloudsmith-cli

      # Download artifact from previous workflow (if applicable)
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist/  # Updated path here to 'dist/'
          repository: ${{ github.repository }}
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
          

      # List directory contents (for debugging)
      - name: List directory contents
        run: ls -la /home/runner/work/cloudsmith-cs-interview-candidate/cloudsmith-cs-interview-candidate/dist #updated path here to 'dist/'

      # Push package to Cloudsmith
      - name: Push package to Cloudsmith
        run: |
          if ! ls /home/runner/work/cloudsmith-cs-interview-candidate/cloudsmith-cs-interview-candidate/dist/example_package-0.1.0.tar.gz 1> /dev/null 2>&1; then  # Updated path here to 'dist/'
            echo "No package found to upload"
            exit 1
          fi
          cloudsmith push python ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_REPOSITORY }} dist/*.tar.gz --republish  # Updated path here to 'dist/'
