name: Publish Python Package

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed
    branches:
      - master

permissions:
  id-token: write  # Required for OIDC authentication
  contents: write
  actions: write

env:
  CLOUDSMITH_NAMESPACE: interview-ashish-dwivedi
  CLOUDSMITH_REPOSITORY: ci-cdtrial
  #CLOUDSMITH_SERVICE_SLUG: ci-cdtrial

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Cloudsmith CLI
      - name: Install Cloudsmith CLI
        run: |
          python -m pip install --upgrade pip
          pip install cloudsmith-cli twine

      # Download artifact from previous workflow (if applicable)
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist/  # Updated path here to 'dist/'
          repository: ${{ github.repository }}
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
          
      # Authenticate with Cloudsmith using OIDC
      - name: Authenticate with Cloudsmith
        run: |
          # Use GitHub OIDC token for authentication
          cloudsmith login \
            --username "${{ github.actor }}" \
            --oidc-provider github \
            --oidc-token "${{ steps.id-token.outputs.id-token }}"

      # List and verify package contents
      - name: Verify package
        run: |
          echo "Listing package contents:"
          ls -la dist/
          
          # Check if package exists
          if [ -z "$(ls -A dist/*.tar.gz 2>/dev/null)" ]; then
            echo "No package found to upload"
            exit 1
          fi

      # Push package to Cloudsmith
      - name: Push package to Cloudsmith
        run: |
          for package in dist/*.tar.gz dist/*.whl; do
            if [ -f "$package" ]; then
              echo "Publishing $package"
              cloudsmith push python \
                "${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_REPOSITORY }}" \
                "$package" \
                --republish
            fi
          done
