name: Publish Python Package

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed
    branches:
      - master

permissions:
  id-token: write  # Required for OIDC authentication
  contents: write
  actions: write

env:
  CLOUDSMITH_NAMESPACE: Interview-Ashish-Dwivedi
  CLOUDSMITH_REPOSITORY: ci-cdtrial
  #CLOUDSMITH_API: fcb2aefedb5552145793c1cfae1d28ac3f2528bd

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Cloudsmith CLI
      - name: Install Cloudsmith CLI
        run: |
          python -m pip install --upgrade pip
          pip install cloudsmith-cli

      # Download artifact from previous workflow (if applicable)
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist/
        
          repository: ${{ github.repository }}
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      # List directory contents (for debugging)
      - name: List directory contents
        run: ls -la dist/

      # Push package to Cloudsmith using API key for authentication
      # Authenticate with Cloudsmith
      - name: Authenticate with Cloudsmith
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          cloudsmith whoami || cloudsmith login -u ${{ github.actor }}

      # Push package to Cloudsmith
      - name: Push package to Cloudsmith
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          cloudsmith push python ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_REPOSITORY }} dist/*.tar.gz --republish
