name: Publish Python Package to Cloudsmith

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types: [completed]
    branches: [master]

permissions:
  contents: write
  actions: write

env:
  CLOUDSMITH_NAMESPACE: Interview-Ashish-Dwivedi
  CLOUDSMITH_REPOSITORY: ci-cdtrial

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cloudsmith-cli twine setuptools wheel

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist/
          repository: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Debug Artifact Information
        run: |
          echo "Listing dist directory contents:"
          ls -la dist/
          echo "Checking package files:"
          file dist/*.tar.gz || echo "No .tar.gz files found"
          file dist/*.whl || echo "No .whl files found"

      - name: Verify Cloudsmith Configuration
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          echo "Checking Cloudsmith configuration..."
          cloudsmith whoami
          cloudsmith list repos

      - name: Publish to Cloudsmith
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          echo "Attempting to publish package..."
          for package in dist/*.tar.gz dist/*.whl; do
            if [ -f "$package" ]; then
              echo "Publishing $package"
              cloudsmith push python \
                "${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_REPOSITORY }}" \
                "$package" \
                --republish
            fi
          done
